### ISSUE TITLE
[Question] Does it always return a 3-sentence summary?

### ISSUE THREAD

**Issue by jlia0** [danielvarab/GenX#1]
Is there any way to extend the summary length?

**Comment by danielvarab** [comment]
Hi! There most certainly is. For most of the implementations in the repo, you can specify a desired length through the `max_length` argument. e.g. 

```python
checkpoint = 'Yale-LILY/brio-cnndm-uncased'
genx = Cached.from_pretrained(checkpoint)

text = .. # pick some text here :)
sents = nltk.sent_tokenize(text)
output = genx(text, sents, max_length=2) # <----
print(output["summary"])
```

Check out the code in `inference.py` for more details. I'll try to push some more documentation after the summer!
